### ISSUE TITLE
Array spread syntax is not supported

### ISSUE THREAD

**Issue by dungwinux** [ocelot-ide/ElementaryJS#200]
- ElemetaryJS Version: 1fa2c10

### Problem
When attempting to use spread operator on an array, ElementaryJS encountered an unknown error. This issue also affects the live version at https://code.ocelot-ide.org/

### Steps to Reproduce:

1. Input the below javascript code:
```js
[...[1, 2]].length
```

#### Expected value

```
2
```

#### Actual behavior

It throws error and give the message as shown below:
```
TypeError: unknown: Property init of VariableDeclarator expected node to be of a type ["Expression"] but instead got "SpreadElement"
```

#### Jest output

```
 FAIL  tests/spread.test.ts (6.095 s)
  ● ElementaryJS - Spread › Spread issue

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: [TypeError: unknown: Property init of VariableDeclarator expected node to be of a type ["Expression"] but instead got "SpreadElement"]

      3 | describe("ElementaryJS - Spread", () => {
      4 |     test("Spread issue", async () => {
    > 5 |         await expect(run(`[...[1, 2]].length`)).resolves.toEqual(2);
        |               ^
      6 |     });
      7 | });
      8 | 

      at expect (node_modules/expect/build/index.js:134:15)
      at tests/spread.test.ts:5:15
      at tests/spread.test.ts:8:71
      at Object.<anonymous>.__awaiter (tests/spread.test.ts:4:12)
      at Object.<anonymous> (tests/spread.test.ts:4:37)

 PASS  tests/ejs-environments.test.ts (6.794 s)
 PASS  tests/ejs.test.ts (13.463 s)
 PASS  tests/ejs-test-mode.test.ts (25.029 s)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 147 passed, 148 total
Snapshots:   0 total
Time:        25.668 s
Ran all test suites.
```

**Comment by arjunguha** [comment]
EJS spread is not supported. In principle, it is easy to do. In practice, someone needs to do it.

**Comment by arjunguha** [comment]
Documented this in the readme. Closing.
